Feature/sign up
wolox-training/ma-express-js pull request #3
Opened 2020-12-22 12:34 UTC by elcorren

## Summary
- User sign-up finished

## Known Issues
None

## Trello Card
https://trello.com/c/BOllKerz/35-sign-up

2020-12-22 18:03 UTC, FrancoCoronel requested changes

2020-12-22 18:03 UTC, FrancoCoronel commented on app/controllers/users.js
> +  } catch (error) {
Depending in how you handle error, this code probably will be change.
Follow the logic of this files

/app/errors.js
/app/middlewares/errors.js

2020-12-22 18:03 UTC, FrancoCoronel commented on app/controllers/users.js
> +const emailValidation = email => {
What happen if the sended email is...

1. "        @wolox.com.ar"
2. "@wolox.com.ar      "
3. "    @wolox.com.ar    "

2020-12-22 18:17 UTC, elcorren commented on app/routes.js
> +  app.post('/users', register);
It is true! The name signUp is more transparent for this endpoint. But the first list item on the card is to implement /users endpoint.

2020-12-23 15:11 UTC, FrancoCoronel requested changes

2020-12-23 15:11 UTC, FrancoCoronel commented on app/controllers/users.js
> +    if (!userValid) throw errors.createUserError('Missing fields.');
createUserError is generic, I think that invalidParamsError is more specific. In this case, something went wrong with params. What do yo think??

2020-12-23 15:11 UTC, FrancoCoronel commented on app/controllers/users.js
> +    if (!validEmail) throw errors.createUserError('Invalid email.');
same, email is not correct (invalid param error)

2020-12-23 15:11 UTC, FrancoCoronel commented on app/controllers/users.js
> +    if (!validPass) throw errors.createUserError('Invalid password.');
same, password is invalid (Invalid param error)

2020-12-23 15:11 UTC, FrancoCoronel commented on app/controllers/users.js
> +    if (emailExists) throw errors.createUserError('Email already exists.');
In this case, the email exists... so here could be uniqueEmailError. Are you agree?

2020-12-23 15:13 UTC, FrancoCoronel requested changes

2020-12-23 15:13 UTC, FrancoCoronel commented on app/services/users.js
> +exports.emailExists = email => User.findOne({ where: { email } });
You handle de databaseError here:
```.js
exports.verifyEmailUnique = email =>
  User.findOne({ where: { email } }).catch(error => {
    logger.error('Error while trying to get user by email', error.message);
    throw errors.databaseError(error.message);
  });
```

2020-12-23 15:13 UTC, FrancoCoronel commented on app/services/users.js
> +exports.create = (email, password, name, lastName) => User.create({ email, password, name, lastName });
Its better if you catch de error here directly:
```.js
exports.createUser = userData =>
  User.create(userData).catch(error => {
    logger.error('Error while trying to create user', error.message);
    throw errors.databaseError(error.message);
  });
```

2020-12-23 16:41 UTC, FrancoCoronel requested changes

2020-12-23 16:41 UTC, FrancoCoronel commented on app/services/users.js
> +exports.emailExists = email => {
If you are returning the query response without mapping the result, you can write this function as:
```.js
exports.emailExists = email =>
  User.findOne({ where: { email } }).catch(error => {
    logger.error('Error while trying to get user by email', error.message);
    throw errors.databaseError(error.message);
  });
```

2020-12-23 16:41 UTC, FrancoCoronel commented on app/services/users.js
> +exports.create = (email, password, name, lastName) => {
idem than emailExists

2020-12-23 16:53 UTC, FrancoCoronel approved these changes
Great Job Tincho !!!

2020-12-23 16:56 UTC, merged